CC=gcc
cflags= -Wall -lm
out=lab1
#Pruebas
#./lab1 -i prueba_10.txt -o salida.txt -b
#./lab1 -i prueba_100.txt -o salida.txt -b
#./lab1 -i prueba_500.txt -o salida.txt -b
#./lab1 -i prueba_1000.txt -o salida.txt -b
all:
	$(CC) Lab1.c -o $(out) $(cflags)
clean:
	rm $(out)